<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'MyFatoorah\\Library\\' => array($vendorDir . '/myfatoorah/library/src'),
    'MyFatoorah\\LaravelPackage\\' => array($vendorDir . '/myfatoorah/laravel-package/src'),
);
