<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '25816eff4fe327907d5e058e7312d09b' => $vendorDir . '/myfatoorah/library/autoload.php',
);
