<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1c7bdca97ea775839db946d4ccc102bd
{
    public static $files = array (
        '25816eff4fe327907d5e058e7312d09b' => __DIR__ . '/..' . '/myfatoorah/library/autoload.php',
    );

    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MyFatoorah\\Library\\' => 19,
            'MyFatoorah\\LaravelPackage\\' => 26,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MyFatoorah\\Library\\' => 
        array (
            0 => __DIR__ . '/..' . '/myfatoorah/library/src',
        ),
        'MyFatoorah\\LaravelPackage\\' => 
        array (
            0 => __DIR__ . '/..' . '/myfatoorah/laravel-package/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1c7bdca97ea775839db946d4ccc102bd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1c7bdca97ea775839db946d4ccc102bd::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1c7bdca97ea775839db946d4ccc102bd::$classMap;

        }, null, ClassLoader::class);
    }
}
